# Generated by Django 5.1.5 on 2025-01-23 19:08

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'A user with that email already exists'}, max_length=254, unique=True, verbose_name='email address')),
                ('is_verified', models.BooleanField(db_index=True, default=False, verbose_name='email verified')),
                ('full_name', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]{2,}$')], verbose_name='full name')),
                ('phone_number', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='phone number')),
                ('street_address', models.CharField(max_length=255, verbose_name='street address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('postal_code', models.CharField(max_length=20, verbose_name='postal code')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('state_or_region', models.CharField(blank=True, max_length=100, verbose_name='state/region')),
                ('vat_number', models.CharField(blank=True, max_length=50, verbose_name='VAT number')),
                ('accepted_terms', models.BooleanField(db_index=True, default=False, verbose_name='accepted terms')),
                ('marketing_consent', models.BooleanField(default=False, verbose_name='marketing consent')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'indexes': [models.Index(fields=['email', 'is_verified'], name='users_custo_email_e94323_idx'), models.Index(fields=['is_staff', 'is_active'], name='users_custo_is_staf_2f15ad_idx')],
            },
        ),
    ]
