# Generated by Django 5.1.4 on 2025-01-13 21:18

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="accepted_terms",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user has accepted the Terms of Service.",
                verbose_name="accepted terms",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="city"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.CharField(blank=True, max_length=100, verbose_name="country"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date joined"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "A user with that email already exists."},
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="full name"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user account should be considered active.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into the admin site.",
                verbose_name="staff status",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user has verified their email address.",
                verbose_name="email verified",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="marketing_consent",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user has consented to marketing communications.",
                verbose_name="marketing consent",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in format: '+999999999'. Up to 15 digits.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="postal code"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="state_or_region",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="state/region"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="street_address",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="street address"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="vat_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="VAT number"
            ),
        ),
    ]
