# Generated by Django 5.1.4 on 2025-01-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=100)),
                ("services", models.CharField(max_length=200)),
                ("year", models.CharField(max_length=4)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("category", models.CharField(max_length=100)),
                ("link", models.CharField(max_length=200)),
                ("external_link", models.URLField(blank=True, null=True)),
                ("featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
