# Generated by Django 5.1.4 on 2025-01-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "client_specifications",
                    models.FileField(
                        blank=True,
                        help_text="Client-provided documents for project customization.",
                        null=True,
                        upload_to="client_specs/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning Phase"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("enterprise", "Enterprise Full-Stack Solution"),
                            ("mid_tier", "Mid-Tier Solution"),
                            ("static", "Static Frontend Solution"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("features", models.JSONField()),
                ("tech_stack", models.JSONField(default=list)),
                ("deliverables", models.JSONField(default=list)),
                (
                    "estimated_duration",
                    models.IntegerField(help_text="Duration in days"),
                ),
                (
                    "maintenance_period",
                    models.IntegerField(default=30, help_text="Days of support"),
                ),
                (
                    "sla_response_time",
                    models.IntegerField(default=24, help_text="Response time in hours"),
                ),
            ],
        ),
    ]
