# Generated by Django 5.1.5 on 2025-02-02 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectaddon',
            name='addon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.addon'),
        ),
        migrations.AddField(
            model_name='projectaddon',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='addons',
            field=models.ManyToManyField(related_name='projects', through='projects.ProjectAddon', to='projects.addon'),
        ),
        migrations.AddField(
            model_name='project',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projectpackage'),
        ),
        migrations.AddField(
            model_name='addon',
            name='compatible_packages',
            field=models.ManyToManyField(related_name='compatible_addons', to='projects.projectpackage'),
        ),
        migrations.AlterUniqueTogether(
            name='projectaddon',
            unique_together={('project', 'addon')},
        ),
    ]
