# Generated by Django 5.1.5 on 2025-01-28 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_staff',
            field=models.ManyToManyField(blank=True, help_text='Staff members assigned to this project', related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(help_text='Project owner', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='package',
            field=models.ForeignKey(blank=True, help_text='Selected project package', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projectpackage'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'created_at'], name='projects_pr_status_7ee874_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'created_at'], name='projects_pr_user_id_29bec8_idx'),
        ),
    ]
