# Generated by Django 5.1.5 on 2025-02-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('projects', '0003_seed_default_packages'),
    ]

    operations = [
    ]
