[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3

[tool.black]
line-length = 88
target-version = ["py39"]

[tool.pytest]
DJANGO_SETTINGS_MODULE = "backend.settings"
python_files = "tests.py test_*.py *_tests.py"
addopts = "--nomigrations --cov=. --cov-report=html"
