# Generated by Django 5.1.6 on 2025-02-13 18:42

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_initial'),
        ('projects', '0004_merge_0002_initial_0003_seed_default_packages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plannersubmission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='plannersubmission',
            name='website_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plannersubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='plannersubmission',
            name='submission_data',
            field=models.JSONField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='plannersubmission',
            index=django.contrib.postgres.indexes.GinIndex(fields=['submission_data'], name='planner_pla_submiss_e40076_gin'),
        ),
    ]
