# Generated by Django 5.1.6 on 2025-02-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_plannersubmission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannersubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
