# Generated by Django 5.1.6 on 2025-02-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_alter_plannersubmission_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannersubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
